# Generated by Django 3.2.6 on 2022-05-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tjournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataBase', models.CharField(max_length=256)),
                ('LevelRecord', models.CharField(blank=True, max_length=256)),
                ('DateRecord', models.DateTimeField(blank=True, null=True)),
                ('Application', models.CharField(blank=True, max_length=256)),
                ('Computer', models.TextField(blank=True, max_length=256)),
                ('Event', models.TextField(max_length=256)),
                ('Comment', models.TextField(blank=True, max_length=256)),
                ('MetaData', models.TextField(blank=True, max_length=256)),
                ('DataRecord', models.TextField(blank=True, max_length=256)),
                ('DataPresentationRecord', models.TextField(blank=True, max_length=256)),
                ('ApplicationPresentation', models.TextField(blank=True, max_length=256)),
                ('EventPresentation', models.TextField(blank=True, max_length=256)),
                ('MetaDataPresentation', models.TextField(blank=True, max_length=256)),
                ('Transaction_status', models.CharField(blank=True, max_length=256)),
                ('Transaction_id', models.TextField(blank=True, max_length=256)),
                ('Session', models.SmallIntegerField(blank=True, null=True)),
                ('Connection', models.IntegerField(blank=True, null=True)),
                ('ServerName', models.CharField(blank=True, max_length=256)),
                ('Port', models.SmallIntegerField(blank=True, null=True)),
                ('SyncPort', models.TextField(blank=True, max_length=256)),
                ('SessionDataSeparation', models.TextField(blank=True, max_length=256)),
                ('SessionDataSeparationPresentation', models.TextField(blank=True, max_length=256)),
                ('User', models.CharField(blank=True, max_length=256)),
                ('UidUse', models.CharField(blank=True, max_length=256)),
                ('UserName', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Tjournals',
            },
        ),
    ]
