# Generated by Django 3.2.6 on 2022-05-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tjournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tjournal',
            options={},
        ),
        migrations.AlterModelTable(
            name='tjournal',
            table='employee',
        ),
    ]
