# Generated by Django 3.2.6 on 2022-05-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220512_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tjournal',
            options={'verbose_name_plural': 'Tjournals'},
        ),
        migrations.AlterModelTable(
            name='tjournal',
            table=None,
        ),
    ]
